### ISSUE TITLE
Custom UI for crowdsourcing users

### ISSUE THREAD

**Issue by nightsh** [okfn/crowdsourced-surveys#11]
We currently have the option to embed forms as iframes. We need to know more about this feature, what can and cannot be done, then eventually document it here.

**Comment by pwalsh** [comment]
# Description

Crowdsourcing users will only see the form, and a short "Thank you, the form was submitted successfully." on successful POST of the form. This will be done by embedding the ushahidi form into a static HTML page.

# Tasks

- [ ] Create a new domain `tz-schools.oklabs.org` or similar ( @vitorbaptista can decide on something different )
- [ ] Create a static HTML page which:
  - [ ] embeds the Ushahidi form for our particular survey
  - [ ] shows a thank you message on successful form submission
- [ ] Deploy the static page. Can be to S3, to GitHub Pages, or to Heroku using [this](https://github.com/heroku/heroku-buildpack-static) or a simply Node/Express handler to return an HTML page ( @vitorbaptista to decide )
- [ ] map the domain to the place you host the HTML page

**Comment by pwalsh** [comment]
@nightsh I added description and tasks.

**Comment by pwalsh** [comment]
@nightsh 

- [ ] trying to submit an empty form pops a message, but at the bottom of the iframe, so outside of user's view. User should see error messages.

**Comment by nightsh** [comment]
Uh, that's something that in the not-embedded version should scroll into view. In our case, iframe js doesn't scroll the parent window, and as far as it's concerned, the message is visible due to iframe height being adjusted to match the contents entirely. Not sure how to handle this, how important do you reckon it is?

**Comment by pwalsh** [comment]
@nightsh ok. you can move that into its own issue on the backlog, and close this one.

**Comment by nightsh** [comment]
Opened #16, closing this one
